# Generated by Django 3.2.15 on 2022-08-28 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Feature',
        ),
    ]
