# Generated by Django 3.2.15 on 2022-08-28 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_web', '0002_rename_article_feature'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feature',
            new_name='Service',
        ),
    ]
