# Generated by Django 3.2.15 on 2022-08-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_web', '0003_rename_feature_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
