# Generated by Django 3.2.15 on 2022-08-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_web', '0004_auto_20220828_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlanProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='properties',
            field=models.ManyToManyField(null=True, to='front_web.PricingPlanProperties'),
        ),
    ]
