# Generated by Django 3.2.15 on 2022-08-28 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_web', '0006_auto_20220828_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricingplanproperty',
            options={'verbose_name': 'pricing plan property', 'verbose_name_plural': 'pricing plan properties'},
        ),
    ]
