# Generated by Django 3.2.15 on 2022-08-28 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_web', '0007_alter_pricingplanproperty_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='text',
            new_name='short_description',
        ),
        migrations.AddField(
            model_name='service',
            name='detailed_description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='service_images'),
        ),
    ]
