# Generated by Django 3.2.15 on 2022-08-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_web', '0008_auto_20220829_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.AddField(
            model_name='service',
            name='service_photo',
            field=models.ImageField(blank=True, default='default_service.png', null=True, upload_to='service_images'),
        ),
    ]
