# Generated by Django 3.2.15 on 2022-08-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_web', '0009_auto_20220829_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='detailed_description',
        ),
        migrations.AddField(
            model_name='service',
            name='detailed_description_line1',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='detailed_description_line2',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='detailed_description_line3',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='detailed_description_line4',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='detailed_description_line5',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
