# Generated by Django 4.0.3 on 2022-08-19 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='KM', max_digits=20),
        ),
    ]
