# Generated by Django 4.0.3 on 2022-08-19 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_product_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='date_deleted',
        ),
        migrations.RemoveField(
            model_name='category',
            name='date_deleted',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='date_deleted',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_deleted',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='date_deleted',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='date_deleted',
        ),
        migrations.AlterField(
            model_name='brand',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
