# Generated by Django 3.2.15 on 2022-08-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='KM', max_digits=20, null=True),
        ),
    ]
