# Generated by Django 3.2.15 on 2022-09-08 14:04

from django.db import migrations, models
import django.db.models.deletion
import system.models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20220824_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, default=system.models.get_default_brand, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=system.models.get_default_category, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='customer',
            field=models.ForeignKey(blank=True, default=system.models.get_walkin_customer, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.customer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_unit',
            field=models.ForeignKey(default=system.models.get_default_product_unit, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.unit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, default=system.models.get_generic_supplier, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.supplier'),
        ),
    ]
