# Generated by Django 3.2.15 on 2022-09-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20220908_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_cost',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
